title: dash
author: ferroscraft
email: ferroscraft@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  apenas um site com coisas que eu considero interessantes, espero que goste <3
show_excerpts: true # set to true to show excerpts on the homepage

paginate: 7
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: ferroscraft

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://www.facebook.com/ferros.craft.96/
      icon: facebook-square
      color: cyan
    - url: https://www.youtube.com/ferroscraft
      icon: youtube-square
      color: red
    - url: https://github.com/ferroscraft
      icon: github-square
      color: purple

  show_author: true

  animation_speed: 30

# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging

# Replaces the default avatar provider (gravatar)
#avatar_source: github
github_username: ferroscraft
